Move common attributes to resource attributes
signalfx/splunk-otel-js-web pull request #212
Opened 2021-07-07 14:02 UTC by t2t2

Added [relevant resource telemetry sdk attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#telemetry-sdk), some duplicate currently existing, keeping both around for backwards compat.

Zipkin exporter [copies them from resource to output span tags](https://github.com/open-telemetry/opentelemetry-js/blob/3a327ddea7ab46e686beb765cba5bf4f73a90b94/packages/opentelemetry-exporter-zipkin/src/transform.ts#L86) which means to backend there should be no differences (other than a few added tags)

2021-07-07 14:43 UTC, jtmalinowski commented
I'd prefer not modifying Zipkin like that, because if we stick to standards, it lets us work across different languages / stacks. Our discussions are also based on based on adherence to standards, e.g. https://github.com/signalfx/gdi-specification/pull/112

2021-07-07 14:44 UTC, jtmalinowski requested changes
I'd prefer not modifying Zipkin like that, because if we stick to standards, it lets us work across different languages / stacks. Our discussions are also based on based on adherence to standards, e.g. signalfx/gdi-specification#112

2021-07-07 15:01 UTC, t2t2 commented
> I'd prefer not modifying Zipkin like that

Uhhh what modifications tho

* This is completely using otel-s default behavior when it comes to zipkin exporter (so no modifications, if anything it removes existing differences (forcing empty resource))
* [Using resources is following the otel standards for sending such data](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service) and should other exporters (specifically otlp/json) be important it will align to how that data structure exports data (instead of it copied to every data otlp/json has it only once at the root level)

2021-07-08 14:58 UTC, johnbley commented on test/init.test.ts
> +    assert.ok(exposedSpan.resource.attributes['telemetry.sdk.name'], 'Checking splunk.rumSessionId');
Copied+pasted assert messages here.

2021-07-09 09:16 UTC, jtmalinowski approved these changes
@t2t2 just document our modifications to zipkin exporter please?

2021-07-09 09:34 UTC, mhennoch approved these changes

2021-07-09 10:26 UTC, merged