Async context: Improve hash based router support, note on code splitting
signalfx/splunk-otel-js-web pull request #224
Opened 2021-07-29 12:12 UTC by t2t2

Improve async context context manager support for hash based routers and add a note to documentation about code split usage.

## Hash based router:

[Angularjs' router](https://github.com/angular/angular.js/blob/9bff2ce8fb170d7a33d3ad551922d7e23e9f82fc/src/ng/browser.js#L242) changes the hash and then waits for browser to fire hashchange event to do rest of the transition (load components, fire them, etc...). Added linking context in that case by watching if location.hash value changed within the function called with contextmanager.with

## Note on lazy loading

We can't link code executed in <script> tag that was loaded by user interaction, so added a note to documentation on how it can be supported.

2021-07-29 12:19 UTC, t2t2 commented
@theletterf @gschatz-splunk For some reason doesn't seem to add `@signalfx/docs` to reviewers nor either of you manually, probably some permission thing to figure out

<img width="330" alt="image" src="https://user-images.githubusercontent.com/1122555/127490424-edcef761-fe74-42d7-827e-b2fe46cc5a33.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/1122555/127490534-88c149ad-987e-4b2f-a0bf-e374f8269552.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/1122555/127490575-ee5265c5-a00b-4bbf-bdab-f3030dc31cc6.png">

2021-07-29 13:51 UTC, theletterf commented
@t2t2 Weird. Could you ask around?

2021-07-30 10:51 UTC, theletterf requested changes

2021-07-30 10:51 UTC, theletterf commented on CHANGELOG.md
> +- Improve asynronous context for hash based routers
```suggestion
- Improve asynchronous context for hash-based routers
```

2021-07-30 10:51 UTC, theletterf commented on docs/Async-Traces.md
> +* Hash based routers
```suggestion
* Hash-based routers
```

2021-07-30 10:51 UTC, theletterf commented on docs/Async-Traces.md
> +
```suggestion
There are also limitations when using code splitting: only code loaded by promise-based implementations gets linked to the parent interaction. For an example, see [webpack's ìmport() syntax`](https://webpack.js.org/guides/code-splitting/#dynamic-imports).

```

2021-07-30 12:18 UTC, theletterf approved these changes

2021-08-04 10:33 UTC, mhennoch approved these changes

2021-08-04 13:00 UTC, merged