Add version configuration option
signalfx/splunk-otel-js-web pull request #419
Opened 2022-08-18 09:09 UTC by t2t2

# Description

Adds version configuration option that sets `app.version` attribute on spans

## Type of change

- New feature (non-breaking change which adds functionality)
- Documentation update

# How has this been tested?

- Added unit tests

2022-08-18 09:11 UTC, theletterf requested changes

2022-08-18 09:11 UTC, theletterf commented on docs/Configuration.md
> +|`version`|`string`|`(none)`|Sets app version for all the spans, used to distinguish between different version deployments. (eg. `1.0.1`, `20220820`) |
```suggestion
|`version`|`string`|`(none)`|Sets app version for all the spans, used to distinguish between different version deployments. For example: `1.0.1` or `20220820` |
```

2022-08-18 10:23 UTC, theletterf approved these changes

2022-08-26 07:26 UTC, mhennoch approved these changes

2022-08-26 07:26 UTC, merged